sr/entry/urls.py
from django.urls import path

from entry.views import EntryListView, EntryCreateView, EntryUpdateView, EntryDeleteView


app_name = 'entry'


urlpatterns = [
    path('', EntryListView.as_view(), name='list'),
    path('create/', EntryCreateView.as_view(), name='create'),
    path('<int:id>/delete/', EntryDeleteView.as_view(), name='delete'),
    path('<int:id>/', EntryUpdateView.as_view(), name='update'),
]

sr/sr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from rest_framework.authtoken import views
from graphene_django.views import GraphQLView

from sr.views import SRLoginView
from entry.rest_views import EntryViewSet


router = routers.DefaultRouter()
router.register('entries', EntryViewSet)


urlpatterns = [
    path('', RedirectView.as_view(url='entry')),
    path('admin/', admin.site.urls),
    path('user/login/', SRLoginView.as_view()),
    path('user/logout/', LogoutView.as_view(), name="logout"),
    path('entry/', include('entry.urls', namespace="entry")),
    path('api/', include(router.urls)),
    path('api/auth/', views.obtain_auth_token),
    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True)))
]

sr/entry/models.py
from django.db import models
from django.contrib.auth.models import User


class EntryQuerySet(models.QuerySet):
    def search(self, criteria):
        return self.filter(models.Q(title__contains=criteria) | models.Q(content__contains=criteria))


class EntryManager(models.Manager):
    def get_queryset(self):
        return EntryQuerySet(self.model, using=self._db)


class Entry(models.Model):
    title = models.CharField(max_length=30)
    content = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    objects = EntryManager()

sr/entry/forms.py
from django import forms

from entry.models import Entry


class EntryForm(forms.ModelForm):
    title = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(max_length=100, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))

    class Meta:
        model = Entry
        fields = ['title', 'content']

    def set_user(self, user):
        self.user = user

    def save(self, commit=True):
        entry = super().save(commit=False)
        if not entry.id:
            entry.user = self.user
        entry.save()
        return entry

sr/sr/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.utils.translation import gettext_lazy as _


class SRAuthenticationForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control first', 'placeholder': _("Username")}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control mb-3 last', 'placeholder': _("Password")}),
    )

sr/entry/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse

from entry.models import Entry
from entry.forms import EntryForm


@method_decorator(login_required, name='dispatch')
class EntryListView(ListView):
    model = Entry
    template_name = 'entry/list.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.GET.get('q', ''):
            return queryset.search(self.request.GET.get('q'))
        return queryset


@method_decorator([login_required, permission_required('entry.add_entry')], name='dispatch')
class EntryCreateView(CreateView):
    form_class = EntryForm
    model = Entry

    def get_success_url(self):
        return reverse('entry:list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form.set_user(request.user)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


@method_decorator([login_required, permission_required('entry.change_entry')], name='dispatch')
class EntryUpdateView(UpdateView):
    form_class = EntryForm
    model = Entry
    pk_url_kwarg = 'id'

    def get_success_url(self):
        return reverse('entry:list')


@method_decorator([login_required, permission_required('entry.delete_entry')], name='dispatch')
class EntryDeleteView(DeleteView):
    model = Entry
    pk_url_kwarg = 'id'

    def get_success_url(self):
        return reverse('entry:list')

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

sr/sr/views.py
from django.contrib.auth.views import LoginView

from sr.forms import SRAuthenticationForm


class SRLoginView(LoginView):
    authentication_form = SRAuthenticationForm
    extra_context = {"title_page": "Login"}
    redirect_authenticated_user = True

sr/entry/templates/entry/entry_form.html
{% extends "entry/layout.html" %}

{% load static %}

{% block main %}
  <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="{{form.title.id_for_label}}">{{form.title.label}}</label>
      {{form.title}}
    </div>
    <div class="mb-3">
      <label for="{{form.content.id_for_label}}">{{form.content.label}}</label>
      {{form.content}}
    </div>
    {% if not form.instance.id %}
      <button class="btn btn-primary" type="submit" value="Save">Create</button>
    {% else %}
      <button class="btn btn-primary" type="submit" value="Save">Update</button>
    {% endif %}
  </form>
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/entry/layout.css"%}">
{% endblock %}

sr/entry/templates/entry/layout.html
{% extends "base.html" %}

{% block content %}
  <nav class="navbar navbar-dark bg-dark sticky-top flex-md-nowrap p-0">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">SR</a>
    <ul class="navbar-nav px-3">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Sign out</a>
      </li>
    </ul>
  </nav>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
        <div class="sidebar-content">
          <h6 class="px-3 mt-4 mb-1 text-muted">Entry</h6>
          <ul class="nav flex-column">
            {% if perms.entry.add_entry %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.namespace == 'entry' and request.resolver_match.url_name == 'create' %}disabled{% endif %}" href="{% url 'entry:create'%}">Create</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.namespace == 'entry' and request.resolver_match.url_name == 'list' %}disabled{% endif %}" href="{% url 'entry:list'%}">List</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="col-md-9 ml-sm-auto col-lg-10">
        {% block main %}{% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

sr/entry/templates/entry/list.html
{% extends "entry/layout.html" %}

{% load static %}

{% block main %}
  <div class="row">
    {% for entry in object_list %}
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title">{{entry.title}}</h5>
          <p class="card-text">{{entry.content}}</p>
          {% if perms.entry.change_entry %}
          <div class="btn-group">
            <a href="{% url 'entry:update' entry.id %}" class="btn btn-outline-secondary">Change</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

{% block css %}
  <link rel="stylesheet" href="{% static "css/entry/layout.css"%}">
{% endblock %}

sr/sr/templates/base.html
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{title_page}}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  {% block css %}{% endblock %}
</head>
<body>
 {% block content %}{% endblock %}
</body>
</html>